// Local Capacitor plugin that reads distance data from HealthKit so the
// distance-tracking flow can use Apple Watch / Apple Fitness as an authoritative
// source. Workouts (running, walking, cycling, skating, swimming, etc.) record
// their own totalDistance via the watch's motion classifier and GPS, which is
// dramatically more accurate than what CMPedometer or our coarse background
// GPS runner can produce — particularly for non-walking activities like
// skating where step counters report zero.
//
// Capacitor auto-discovers ObjC-visible CAPPlugin subclasses in the app target
// at runtime; no Package.swift edit is needed (and shouldn't be — the SPM
// Package.swift is regenerated by `cap sync`).

import Capacitor
import Foundation
import HealthKit

@objc(HealthKitDistancePlugin)
public class HealthKitDistancePlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "HealthKitDistancePlugin"
    public let jsName = "HealthKitDistance"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "isAvailable", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "requestAuthorization", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "getActivityDistance", returnType: CAPPluginReturnPromise)
    ]

    private let healthStore = HKHealthStore()

    @objc func isAvailable(_ call: CAPPluginCall) {
        call.resolve(["available": HKHealthStore.isHealthDataAvailable()])
    }

    @objc func requestAuthorization(_ call: CAPPluginCall) {
        guard HKHealthStore.isHealthDataAvailable() else {
            call.resolve(["granted": false])
            return
        }

        var readTypes = Set<HKObjectType>()
        readTypes.insert(HKObjectType.workoutType())
        if let t = HKObjectType.quantityType(forIdentifier: .distanceWalkingRunning) { readTypes.insert(t) }
        if let t = HKObjectType.quantityType(forIdentifier: .distanceCycling) { readTypes.insert(t) }
        if let t = HKObjectType.quantityType(forIdentifier: .distanceWheelchair) { readTypes.insert(t) }
        if let t = HKObjectType.quantityType(forIdentifier: .distanceSwimming) { readTypes.insert(t) }
        if let t = HKObjectType.quantityType(forIdentifier: .distanceDownhillSnowSports) { readTypes.insert(t) }
        // Skating sports landed in iOS 17 — guard so older OS versions still compile/run.
        if #available(iOS 17.0, *) {
            if let t = HKObjectType.quantityType(forIdentifier: .distanceSkatingSports) { readTypes.insert(t) }
        }

        healthStore.requestAuthorization(toShare: nil, read: readTypes) { success, error in
            if let error = error {
                call.reject("HealthKit authorization failed: \(error.localizedDescription)")
                return
            }
            // HKHealthStore can return success=true with no actual grant when the
            // user denies — there is no API to inspect read authorization status
            // directly (Apple's privacy stance). The caller infers grant from the
            // distance-query result: zero/null distance means we either weren't
            // granted access or the user did nothing during the window.
            call.resolve(["granted": success])
        }
    }

    @objc func getActivityDistance(_ call: CAPPluginCall) {
        guard HKHealthStore.isHealthDataAvailable() else {
            call.resolve([
                "distance": NSNull(),
                "source": "unavailable"
            ])
            return
        }

        guard let startMs = call.getDouble("start"), let endMs = call.getDouble("end") else {
            call.reject("start and end (milliseconds since epoch) are required")
            return
        }
        if endMs <= startMs {
            call.resolve(["distance": 0, "source": "empty-range"])
            return
        }

        let startDate = Date(timeIntervalSince1970: startMs / 1000)
        let endDate = Date(timeIntervalSince1970: endMs / 1000)
        let predicate = HKQuery.predicateForSamples(withStart: startDate, end: endDate, options: .strictStartDate)

        // Strategy: prefer HKWorkout.totalDistance — that's the watch's own
        // measurement, with proper sport-type classification (skating, cycling,
        // hiking, etc.). If no workouts overlap the window, fall back to summing
        // raw distance samples so passive walking still counts.
        let workoutQuery = HKSampleQuery(
            sampleType: .workoutType(),
            predicate: predicate,
            limit: HKObjectQueryNoLimit,
            sortDescriptors: nil
        ) { [weak self] _, samples, error in
            guard let self = self else { return }
            if let error = error {
                call.reject("workout query failed: \(error.localizedDescription)")
                return
            }
            let workouts = (samples as? [HKWorkout]) ?? []
            var workoutMeters: Double = 0
            for workout in workouts {
                if let distance = workout.totalDistance {
                    workoutMeters += distance.doubleValue(for: HKUnit.meter())
                }
            }

            if workoutMeters > 0 {
                call.resolve([
                    "distance": workoutMeters,
                    "source": "workouts",
                    "workoutCount": workouts.count
                ])
                return
            }

            self.fallbackToDistanceSamples(predicate: predicate, call: call)
        }
        healthStore.execute(workoutQuery)
    }

    private func fallbackToDistanceSamples(predicate: NSPredicate, call: CAPPluginCall) {
        // Sum all distance-flavored quantity samples. Distance categories from the
        // same activity period don't double-count because HealthKit only records
        // one type at a time per sample window.
        var typeIds: [HKQuantityTypeIdentifier] = [
            .distanceWalkingRunning,
            .distanceCycling,
            .distanceWheelchair,
            .distanceSwimming,
            .distanceDownhillSnowSports
        ]
        if #available(iOS 17.0, *) {
            typeIds.append(.distanceSkatingSports)
        }

        let group = DispatchGroup()
        var total: Double = 0
        var firstError: Error? = nil
        let lock = NSLock()

        for identifier in typeIds {
            guard let qtype = HKObjectType.quantityType(forIdentifier: identifier) else { continue }
            group.enter()
            let q = HKStatisticsQuery(
                quantityType: qtype,
                quantitySamplePredicate: predicate,
                options: .cumulativeSum
            ) { _, result, error in
                defer { group.leave() }
                if let error = error {
                    lock.lock()
                    if firstError == nil { firstError = error }
                    lock.unlock()
                    return
                }
                if let sum = result?.sumQuantity() {
                    let meters = sum.doubleValue(for: HKUnit.meter())
                    lock.lock()
                    total += meters
                    lock.unlock()
                }
            }
            healthStore.execute(q)
        }

        group.notify(queue: .main) {
            if total <= 0, let err = firstError {
                call.reject("distance sample query failed: \(err.localizedDescription)")
                return
            }
            call.resolve([
                "distance": total,
                "source": "samples"
            ])
        }
    }
}
